### ISSUE TITLE
Hey There.

### ISSUE THREAD

**Issue by juddey** [Osedea/ignite-native-navigation#1]
Hello,

Just wanted to introduce myself (I suppose you could just click on my avatar, haha). I used your plugin to inspire me (read: borrow lots of code from)  to create `ignite-react-native-navigation` which adds v2 to an ignite project. https://github.com/juddey/ignite-react-native-navigation

Not sure what your thoughts are for v2 but perhaps in the future we could look at merging? Because, srsly, you got the better npm package name.

Feel free to close when you're ready :wave:

**Comment by evang9410** [comment]
Hello @juddey,

It is currently in the works of looking to implement v2 into our repository.

Thanks for reaching out we'll be in touch 👊

**Comment by adrienthiery** [comment]
Hi @juddey, 

That sounds awesome and we would definitely be open to merging in your update 😃

**Comment by juddey** [comment]
Cool. I'll close this out now, ping me at @juddey when you want to talk.
